### ISSUE TITLE
Time Remaining Restarts on Opening Accessory

### ISSUE THREAD

**Issue by mitch7391** [MortJC/homebridge-platform-orbit#9]
Hey @MortJC i noticed while running my station from the B-Hyve app and then I would open HomeKit to check the time remaining it starts counting at 7mins 59s which is not what the B-Hyve app is displaying as my run time; then each time I reopen the accessory it starts counting down from 7mins 59s every time I reopen it, no matter the runtime in the B-Hyve app.

**Comment by MortJC** [comment]
Hi,

Check this again with the updated auto reconnect version.

Cheers James.

**Comment by mitch7391** [comment]
Hey @MortJC I have just updated now, thanks for the speedy work on this :) one thing I did notice upon reboot after the update I saw the following error (all in red) on startup. However, it did not crash homebridge and it does not appear again unless I reboot homebridge server.

[4/20/2020, 18:39:45] [BHyve] WebSocket Error ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [Array], message: [Array], open: [Array], close: [] },
    _retryCount: 0,
    _shouldReconnect: true,
    _connectLock: false,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [],
    onclose: null,
    onerror: null,
    onmessage: null,
    onopen: null,
    _handleOpen: [Function],
    _handleMessage: [Function],
    _handleError: [Function],
    _handleClose: [Function],
    _url: 'https://api.orbitbhyve.com/v1/events',
    _protocols: [],
    _options: { WebSocket: [Function], connectionTimeout: 1000, maxRetries: 10 },
    send: [Function],
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _closeCode: 1006,
      _extensions: {},
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      url: 'https://api.orbitbhyve.com/v1/events',
      _req: [ClientRequest],
      [Symbol(kCapture)]: false
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 9966,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(asyncId)]: 942,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
  
}
(node:18494) UnhandledPromiseRejectionWarning: #<ErrorEvent>
(node:18494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mitch7391** [comment]
It also appears since the update I cannot control from HomeKit anymore and feedback in HomeKit does not update if ran from the Orbit app. HomeKit looks like this if I issue a start (and sprinkler does not start).

![5785552E-F513-44C5-A231-3AFEF103ADFC](https://user-images.githubusercontent.com/40288237/79745031-fda45000-8339-11ea-9f6e-34a12ef96bf9.png)

**Comment by MortJC** [comment]
Hi,

When you say reboot, is that just restarting homebridge app or the whole
server? I don't see that error when I restart my homebridge app.

I've also released another update. Nothing major.

Cheers.

**Comment by mitch7391** [comment]
Hey James, I am using config-ui-x and press the restart icon (which I believe reboots Homebridge not the server, sorry for the wording). I will update after work today and let you know how it goes. 

I am also on the Homebridge beta, but I reverted to normal Homebridge and got the same error when restarting; so I am pretty sure it’s not that.

**Comment by mitch7391** [comment]
Hey @MortJC I just tried the new update and still have the ‘WebSocket Error ErrorEvent‘ upon startup and still the same issues with not being able to control it anymore.

**Comment by MortJC** [comment]
Sorry, what's the issue with not being able to control it?

**Comment by mitch7391** [comment]
So just like the screenshot above, if I issue a start command from HomeKit it just shows as waiting/idle and the sprinklers physically do not start in my garden. When I first installed your plug-in a few revisions go I was able to start the sprinklers from HomeKit.

**Comment by MortJC** [comment]
Right. Not good.

Can you run it I debug and send me the output?

**Comment by mitch7391** [comment]
I can do that for you tonight after work. One other change to my system besides being on Homebridge beta is that a few days ago I also moved from a RPi3 to a RPi4 using the new raspberry pi Homebridge imagine on raspbian lite; however I used the config-ui-x backup and restore feature which means my system should be exactly the same (unless raspbian lite on a RPi4 could be missing anything that regular raspbian had on the RPi3). Just mentioning all potential changes recently just in case :)

**Comment by jamhap64** [comment]
I am having the same issue as Mitch. I installed the plugin tonight and tested. Sprinkler doesn’t start, just says waiting like in Mitch’s screenshot.

**Comment by MortJC** [comment]
Hi, can you run homebridge in debug mode (-D) and send me the output?

**Comment by mitch7391** [comment]
@jamhap64 glad to hear it is not just me. Maybe I haven’t messed anything up :)

**Comment by mitch7391** [comment]
@MortJC I received the same error and not much further info from the debug, but here it all is when I restart homebridge:

[4/22/2020, 19:53:49] [BHyve] Configuring cached device
[4/22/2020, 19:53:49] [BHyve] Configure Irrigation service B-Hyve
[4/22/2020, 19:53:49] [BHyve] Configure Valve service Front Lawn
[4/22/2020, 19:53:49] [BHyve] Configure Valve service Front Garden
[4/22/2020, 19:53:49] [BHyve] Configure Valve service Back Lawn
[4/22/2020, 19:53:49] [BHyve] Configure Valve service Back Garden
[4/22/2020, 19:53:49] [BHyve] openConnection
[4/22/2020, 19:53:49] [BHyve] onMessage
[4/22/2020, 19:53:50] [BHyve] WebSocket Error ErrorEvent {
target: ReconnectingWebSocket {
_listeners: { error: [Array], message: [Array], open: [Array], close: [] },
_retryCount: 0,
_shouldReconnect: true,
_connectLock: false,
_binaryType: 'blob',
_closeCalled: false,
_messageQueue: [],
onclose: null,
onerror: null,
onmessage: null,
onopen: null,
_handleOpen: [Function],
_handleMessage: [Function],
_handleError: [Function],
_handleClose: [Function],
_url: 'https://api.orbitbhyve.com/v1/events',
_protocols: [],
_options: { WebSocket: [Function], connectionTimeout: 1000, maxRetries: 10 },
send: [Function],
_ws: WebSocket {
_events: [Object: null prototype] {},
_eventsCount: 0,
_maxListeners: undefined,
readyState: 2,
protocol: '',
_binaryType: 'nodebuffer',
_closeFrameReceived: false,
_closeFrameSent: false,
_closeMessage: '',
_closeTimer: null,
_closeCode: 1006,
_extensions: {},
_receiver: null,
_sender: null,
_socket: null,
_bufferedAmount: 0,
_isServer: false,
_redirects: 0,
url: 'https://api.orbitbhyve.com/v1/events',
_req: [ClientRequest],
[Symbol(kCapture)]: false
},
_connectTimeout: Timeout {
_idleTimeout: -1,
_idlePrev: null,
_idleNext: null,
_idleStart: 9966,
_onTimeout: null,
_timerArgs: undefined,
_repeat: null,
_destroyed: true,
[Symbol(refed)]: true,
[Symbol(asyncId)]: 942,
[Symbol(triggerId)]: 0
}
},
type: 'error',
message: 'TIMEOUT',
error: Error: TIMEOUT
at ReconnectingWebSocket._handleTimeout (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
at Timeout. (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)

}
(node:18494) UnhandledPromiseRejectionWarning: #
(node:18494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[4/22/2020, 19:53:51] [BHyve] sync
[4/22/2020, 19:53:51] [BHyve] TX {"event":"sync","device_id":"XXXXXXXXXXXXX"}

[4/22/2020, 19:54:14] [BHyve] TX {"event":"ping"}

**(I have replaced the device ID with xxxxxx just in case it was something I should keep hidden)**

**Comment by mitch7391** [comment]
This what I get in debug when I start and stop a zone, however it does not physically start the sprinkler and in Homekit just says waiting/idle (device ID replaced again):

[4/22/2020, 20:06:05] [BHyve] _setValueActive Back Lawn 1
[4/22/2020, 20:06:05] [BHyve] Start zone Back Lawn for 5 mins
[4/22/2020, 20:06:05] [BHyve] startZone 3 5
[4/22/2020, 20:06:05] [BHyve] TX {"event":"change_mode","mode":"manual","device_id":"XXXXXXXXXXXX","timestamp":"2020-04-22T12:06:05.640Z","stations":[{"station":3,"run_time":5}]}

[4/22/2020, 20:06:11] [BHyve] _setValueActive Back Lawn 0
[4/22/2020, 20:06:11] [BHyve] Stop zone Back Lawn
[4/22/2020, 20:06:11] [BHyve] stopZone
[4/22/2020, 20:06:11] [BHyve] TX {"event":"change_mode","mode":"manual","device_id":"XXXXXXXXXXXX","timestamp":"2020-04-22T12:06:11.882Z","stations":[]}

**Comment by MortJC** [comment]
Worked it out. Looks like your system is taking more than 1 second to
connect to the API. I've updated the timeout to 10 seconds.

Version 1.3.2 available.

**Comment by mitch7391** [comment]
Nice find! I wonder why mine takes longer than yours to connect? The new version has fixed the error on startup and I can now control the sprinklers again :) thank you for the quick fix James.

**Comment by mitch7391** [comment]
Statuses seem to be working properly and the time remaining is back to being correct, I will close out these two issues :)

**Comment by jamhap64** [comment]
Works for me also, awesome job with this!
My timer is off 1 minute. It starts countdown at 4 min instead of 5, but not a big deal, just an fyi.
Thanks again!

**Comment by mitch7391** [comment]
Maybe I was a little hasty closing the issue, my is spot on with the timer from what I could see. Feel free to re-open the issue if you like?
